### ISSUE TITLE
Remove arbitrary limit of 90 minutes for editing

### ISSUE THREAD

**Issue by anugupta** [ronalfy/simple-comment-editing#17]
Is there any reason for this hard-coded limit? 

I feel that if we want to use the `sce_comment_time` filter to set a maximum time, then there should not be a hard-coded limit that overrides this.

**Comment by ronalfy** [comment]
The 90 minute limit is for internationalization. For complicated languages like Russian there are multiple words for seconds and minutes depending on what number it is.

The best way I could find is to simply generate those items into a json format and output to the page source as sort of a lookup table. These json variables are cached, but they still need to be generated.

Since I don't want to overload anyone's server with what could theoretically be an indefinite time limit, I limit the filter to what I conside a generous 90 minutes.
